# Generated by Django 5.2.5 on 2025-08-21 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('grade', models.CharField(choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس'), ('7', 'الصف السابع'), ('8', 'الصف الثامن'), ('9', 'الصف التاسع'), ('10', 'الصف العاشر'), ('11', 'الصف الحادي عشر'), ('12', 'الصف الثاني عشر')], max_length=2, verbose_name='الصف')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الطالب')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التوظيف')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'المعلمين',
                'ordering': ['name'],
            },
        ),
    ]
